services:
  backend:
    image: djangowiz/bankapp:latest
    container_name: bankapp
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      TEST_DATABASE_URL: ${TEST_DATABASE_URL}
    volumes:
      - /etc/ssl/certs/private/:/etc/ssl/certs/private/
    restart: unless-stopped

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
      args:
        REACT_APP_API_URL: ${REACT_APP_API_URL}
    ports:
      - "3000:3000"
    environment:
      REACT_APP_API_URL: ${REACT_APP_API_URL}
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../nginx.conf:/etc/nginx/nginx.conf
      - /etc/ssl/certs/private/:/etc/ssl/certs/private/
    depends_on:
      - backend
      - frontend
    restart: unless-stopped




  