name: Deploy with Volume-Mounted Certs

on:
  workflow_run:
    workflows: ['test']
    types:
      - completed

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.versioning.outputs.version }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Extract version
        id: versioning
        run: |
          VERSION=$(grep '^version\s*=' pyproject.toml | cut -d '"' -f2)
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Get commit SHA
        id: sha
        run: |
          echo "short_sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

  build:
    needs: prepare
    runs-on: ubuntu-latest
    environment: production
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: |
            ${{ vars.DOCKERHUB_USERNAME }}/bankapp:latest
            ${{ vars.DOCKERHUB_USERNAME }}/bankapp:${{ needs.prepare.outputs.version }}
            ${{ vars.DOCKERHUB_USERNAME }}/bankapp:${{ needs.prepare.outputs.commit_sha }}
          build-args: |
            COMMIT_SHA=${{ needs.prepare.outputs.commit_sha }}
            BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ')


  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment: production
    
    steps:
      - name: Deploy to Server via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_SERVER_HOST }}
          username: ${{ secrets.SSH_SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd ~/backend

            git fetch origin
            git checkout main
            git reset --hard origin/main

            # Deploy with Docker Compose
            docker compose --file docker-compose.yaml pull
            docker compose --file docker-compose.yaml up -d \
              --force-recreate \
              --remove-orphans \
              --no-deps

            docker ps
            docker image prune -af --filter "until=24h"